name: Trigger auto deployment for backendapi

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/backendapi-AutoDeployTrigger-8ffe619f-4a98-4d9e-8493-069907b679fd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.BACKENDAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.BACKENDAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.BACKENDAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.BACKENDAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.BACKENDAPI_REGISTRY_PASSWORD }}
          containerAppName: backendapi
          resourceGroup: dev_testing
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


